# Generated by Django 5.2.1 on 2025-06-20 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='pakagaes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blog/default.jpg', upload_to='blog/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hotel', models.CharField(max_length=255)),
                ('hotel_stars', models.CharField(choices=[('★', '1 Star'), ('★★', '2 Stars'), ('★★★', '3 Stars'), ('★★★★', '4 Stars'), ('★★★★★', '5 Stars')], default='★★★', max_length=5)),
                ('max_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField()),
                ('Number_of_nights', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
