# Generated by Django 5.2.1 on 2025-06-27 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pakages',
            name='hotel_stars',
            field=models.CharField(choices=[('★', '⭐'), ('★★', '⭐⭐'), ('★★★', '⭐⭐⭐'), ('★★★★', '⭐⭐⭐⭐'), ('★★★★★', '⭐⭐⭐⭐⭐')], default='★★★', max_length=5),
        ),
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.contactmessage')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
