# Generated by Django 5.2.1 on 2025-06-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pakagaes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pakagaes',
            new_name='paksges',
        ),
    ]
