# Generated by Django 5.2.1 on 2025-06-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactmessage_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.contactmessage'),
        ),
    ]
