# Generated by Django 5.2.1 on 2025-06-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_pakagaes_paksges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paksges',
            new_name='pakages',
        ),
    ]
