# Generated by Django 5.2.1 on 2025-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_paksges_pakages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakages',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
